name: Test PR on branch

on:
  push:
    branches:
      - master
  ### make it impossible to push code directly to main/ master
  ### at the same time, run the workflow for all other possible direct pushes to main/ master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  test_pull_request_on_gitbranch:
    runs-on: ubuntu-18.04
    steps:
      - name: Test PR on branch
        run: |
          echo "Pull request"

      - name: List directories
        run: ls -a

      - name: Print date
        run: date

      - name: Text
        run: echo "My name is Gumball"
