name: Deployment pipeline

on:
  push:
    branches:
      - master

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      ### check out the code from repo because virtual env does not have any code
      - uses: actions/checkout@v2

      ### set up node.js to utilize cmd specified in package.json
      - uses: actions/setup-node@v1
        ### 'with' is a parameter of action
        with:
          node-version: '12.x'

      ### install the dependencies above
      - name: npm install
        run: npm install

      ### cmd to run eslint
      - name: lint
        run: npm run eslint

      ### cmd to run build
      - name: build
        run: npm run build

      ### cmd to run test
      - name: test
        run: npm run test

      ### cmd to run e2e testing
      - name: test:e2e
        ### set up cypress to run e2e testing
        uses: cypress-io/github-action@v2
        with:
          ### specify how to run cypress test
          command: npm run test:e2e
          ### start the application before running the cmd
          start: npm run start-prod
          ### specify to wait for the server to be on this url before the test
          wait-on: http://localhost:5000

      ### cmd to push code to heroku
      - name: pushing to heroku
        ### set up heroku for deployment
        uses: akhileshns/heroku-deploy@v3.12.12
        ### specify parameters
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'my-pokedex-pokemon'
          heroku_email: 'vani.dniess.baby@gmail.com'
