name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job_logs_github:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: log github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: log github commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"

      - name: log github commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMITS_MESSAGES"
